AWSTemplateFormatVersion: "2010-09-09"
Description: Parameter File of IAM ROLE

Parameters:
  ProjectName:
    Description: this is base name.
    Type: String
    Default: "TESTPRJ"

Resources:
  #IAMRoleの定義
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      Path: "/"
      ManagedPolicyArns:                    
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  #IAMプロファイル
  IAMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref IAMRole
Outputs:
  IAMProfile:
    Value: !Ref IAMProfile
    Export:
      Name: IAMProfile