AWSTemplateFormatVersion: "2010-09-09"
Description: Parameter File of RDS
#マスターパスワードはパラメータから取得
Parameters:
  ProjectName:
    Description: this is base name.
    Type: String
    Default: TESTPRJ
  MasterUserPassword:
    Type: String
    Description: Password string for master user of DB Instance
    NoEcho: true

#RDSの設定・作成
Resources: 
    #RDSのサブネットも

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${ProjectName}-RDS-subnet"
      DBSubnetGroupDescription:  RDS-subnet
      SubnetIds: 
       - !ImportValue PubSubNAID
       - !ImportValue PubSubNCID
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-RDS-subnet"
  RDSData:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-RDS"
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.32
      MasterUsername: admin
      MasterUserPassword: !Ref MasterUserPassword
      DBName: utrds
      BackupRetentionPeriod: 0
      MultiAZ: true
      PubliclyAccessible: false
      StorageType: gp2
      AllocatedStorage: 20
      StorageEncrypted: true
      CopyTagsToSnapshot: false
      DeletionProtection: false
      DeleteAutomatedBackups: true
      DBSubnetGroupName:  !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !ImportValue RDSSecurityGroupID
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-RDS"